events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Optimizaciones de rendimiento
    sendfile        on;
    keepalive_timeout  65;

    # Configuración del Gateway
    server {
        listen 10000; # Puerto estándar de Render
        server_name localhost;

        # 1. AUTH SERVICE
        location /auth/ {
            proxy_pass http://auth-service:10000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. CATALOG SERVICE
        location /catalog/ {
            proxy_pass http://catalog-service:10000/;
            proxy_set_header Host $host;
        }

        # 3. CART SERVICE
        location /cart/ {
            proxy_pass http://cart-service:10000/;
            proxy_set_header Host $host;
        }

        # 4. ORDER SERVICE
        location /order/ {
            proxy_pass http://order-service:10000/;
            proxy_set_header Host $host;
        }

        # 5. INVENTORY SERVICE
        location /inventory/ {
            proxy_pass http://inventory-service:10000/;
            proxy_set_header Host $host;
        }

        # Salud del Gateway
        location /health {
            return 200 'EcoMod Gateway is Live';
            add_header Content-Type text/plain;
        }
    }
}
