events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # Usamos la variable $PORT que Render nos da
        listen ${PORT};
        server_name localhost;

        location /auth/ {
            proxy_pass http://auth-service:10000/;
            proxy_set_header Host $host;
        }

        location /catalog/ {
            proxy_pass http://catalog-service:10000/;
            proxy_set_header Host $host;
        }

        location /cart/ {
            proxy_pass http://cart-service:10000/;
            proxy_set_header Host $host;
        }

        location /order/ {
            proxy_pass http://order-service:10000/;
            proxy_set_header Host $host;
        }

        location /inventory/ {
            proxy_pass http://inventory-service:10000/;
            proxy_set_header Host $host;
        }

        location /health {
            return 200 'EcoMod Gateway is Live';
            add_header Content-Type text/plain;
        }
    }
}
